### ISSUE TITLE
Input value not being displayed correctly

### ISSUE THREAD

**Issue by sdattatri** [marcocesarato/react-native-input-spinner#15]
Hi,
I have taken the latest version and now there is a slightly different problem.  If I  press the "-" it shows the maximum range value and then switches back and forth between that and the previous step value.

**Comment by marcocesarato** [comment]
What's you lib version? This should be fixed on 1.3.1

**Comment by sdattatri** [comment]
I had version 1.3.0.  Now I have updated it, it seems to work fine.  Thanks.
