### ISSUE TITLE
Feature request: no value & placeholder

### ISSUE THREAD

**Issue by KrisGerhard** [marcocesarato/react-native-input-spinner#16]
It is not possible for the input to have no value at the moment. I think it'd be a nice addition with a placeholder property.

**Comment by marcocesarato** [comment]
Added and published on release **1.3.2** the following proprieties.

| Property               | Description                                                                             | Type             | Default | 
| ---------------------- | --------------------------------------------------------------------------------------- | ---------------- | -------  
| `placeholder`          | The string that will be rendered when text input value is equal to zero                 | String           | `null`  |
| `placeholderTextColor` | The text color of the placeholder string.                                               | String           | `null`  |

## Notes
The placeholder will appear only if the value of the spinner is equal to 0 (zero)
