### ISSUE TITLE
Change color of just one button

### ISSUE THREAD

**Issue by erikadelao13** [marcocesarato/react-native-input-spinner#2]
Hey, i wanted to change the style of only one button, how can i do that with this lib? and i also wanted to change the color of the button when pressed... i dont know if thats possible..

**Comment by marcocesarato** [comment]
It is not possible at the moment but I can implement it. You will see it in the next release :)

**Comment by erikadelao13** [comment]
Thank you so much! I'll be waiting for it!!

**Comment by marcocesarato** [comment]
Added colorLeft, colorRight as prop on 1.1.8.
For change color on press I've added a new example but you can just do something like this:
- On constructor
```
constructor(props){
    super(props);
    this.state = {
        value: 1,
        colorLeft: "#000",
        colorRight: "#000",
    }
}
```
- On render
```
<InputSpinner
    value={this.state.value}
    style={styles.spinner}
    colorLeft={this.state.colorLeft}
    colorRight={this.state.colorRight}
    onChange={(num)=>{
        // ...
        // example of a possible implementation
        const colorLeft = (num > 5 ? "#00F" : "#F00");
        this.setState({
            colorLeft: colorLeft, // New Color
            colorRight: "#0F0", // New Color
        })
    }}/>
```
