### ISSUE TITLE
Allow users to hold buttons as well as repeatedly tap them

### ISSUE THREAD

**Issue by taeh98** [marcocesarato/react-native-input-spinner#21]
Please could you allow users to press and hold the buttons of an input spinner to continually increase or decrease the spinner's value whilst being held as well as allowing the buttons to be repeatedly tapped to increase or decrease the value (as is currently the case)? This would allow the user to use the buttons to select a new value that is much different to the current one much more quickly and easily than if they were only able to change the value by repeatedly tapping the buttons (as is currently the case).

**Comment by marcocesarato** [comment]
Hi, thanks again for your feedback is very appreciated.
I implemented this very useful feature, which I still had in mind and you remembered it so thanks for it.

You will see this changes on the next release.

**Comment by taeh98** [comment]
Thank you very much!
