### ISSUE TITLE
In-built TypeScript support

### ISSUE THREAD

**Issue by taeh98** [marcocesarato/react-native-input-spinner#22]
TypeScript projects can currently only use this package if they also use the third party package @types/react-native-input-spinner. The type definitions in @types/react-native-input-spinner could become out of date if those updating it were to struggle to keep up with changes to this package quickly enough. This could prevent this package working in TypeScript projects.

Please could you, therefore, build TypeScript support into this package itself? This would mean the type conflicts I mentioned would be avoided since the type definitions would always be updated as this package is.

**Comment by marcocesarato** [comment]
Added typescripts definitions on version 1.4.2.
