### ISSUE TITLE
Make spinner values null/undefined when erased instead of 0

### ISSUE THREAD

**Issue by taeh98** [marcocesarato/react-native-input-spinner#28]
At present, when a user uses a keyboard to erase the value of a spinner, its value becomes 0. Since erasing the value is removing it and 0 could be a possible valid value, it should instead be null/undefined. An erased value being 0 instead of null/undefined could also stop validation checks that ensure a value has been given from working. Please could you, therefore, make the value of he spinner (call onChange as) null/undefined when its value is erased by a user using a keyboard?

**Comment by marcocesarato** [comment]
Hi, this is yet possibile using the prop `emptied`.

**Example:**
```
<InputSpinner
        emptied={true} // <=
	step={1}
	max={10}
	min={1}
	value={this.state.value}
	onChange={(value) => {
		this.setState({value: value});
	}}
/>
```

**Comment by taeh98** [comment]
I just checked and that's true. Thank you again!
