### ISSUE TITLE
How utilice onSubmitEditing

### ISSUE THREAD

**Issue by kelvindominguez1595** [marcocesarato/react-native-input-spinner#29]
Could you show me some example using onSubmitEditing
How can it be useful to me?

**Comment by marcocesarato** [comment]
Hi, `onSubmitEditing` is triggered when you click the text input submit button (keyboard button) and it is the same trigger documented [HERE (react-native TextInput component)](https://reactnative.dev/docs/textinput#onsubmitediting).
It could be useful for example if after confirm a quantity you want change screen, ask for something with a modal or change another value after its conirmation etc...

**Example**

```jsx
<Spinner
    value={this.state.value}
    onSubmitEditing={(e) => /* Do something */}
/>
```
