### ISSUE TITLE
Border design on button

### ISSUE THREAD

**Issue by erikadelao13** [marcocesarato/react-native-input-spinner#3]
Hey! I wanted to add a border on a button, i tried with the prop  buttonStyle={{ borderStyle: 'solid', borderColor: '#C4C4C4', borderRadius: 20, borderWidth: 1, }} but i think it is not possible, because it didnt work, i dont know if there is other way?, 

Example of how i want the button to look like:
![image](https://user-images.githubusercontent.com/28150325/61672414-c3bdf480-aca8-11e9-84bd-8e71e59c7c0b.png)

 And sorry for asking too much, but i also wanted to change the color of one button when pressed, but only when is pressed, and once it was pressed i want it to have the same color that it had at the beginning.
Like this
![image](https://user-images.githubusercontent.com/28150325/61672888-a1c57180-acaa-11e9-9573-696591e4b9cb.png)

**Comment by marcocesarato** [comment]
Added colorPress as prop on 1.1.9.
Now the problem with buttonStyle is fixed.

**Comment by erikadelao13** [comment]
What about the buttonTextColor, can it be changed when is pressed?

**Comment by marcocesarato** [comment]
> Thank you, now it works perfectly fine.
> 
> What about the buttonTextColor, can it be changed when is pressed?

Yes, its possible. Wait it on the next release.

**Comment by marcocesarato** [comment]
Added buttonPressStyle and buttonPressTextColor as prop on 1.2.0 and I've added a new example for pressed state customization.

```
<InputSpinner
    value={this.state.value}
    color={"#000"}
    colorPress={"#FFF"}
    buttonTextColor={"#FFF"}
    buttonPressTextColor={"#000"}/>
```

Let me know if you find some issues on this new update :)
