### ISSUE TITLE
Fatal error: Invariant Violation: "outlineWidth" is not a valid style property.

### ISSUE THREAD

**Issue by taeh98** [marcocesarato/react-native-input-spinner#30]
I am getting an invariant violation which I am assuming is from this library because the error matches the buttonRounded stylesheet in /src/Style.js. It is a fatal error that stops the application starting.The error I get is as follows:

Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
- node_modules/react-native/Libraries/LogBox/LogBox.js:117:10 in registerWarning
- node_modules/react-native/Libraries/LogBox/LogBox.js:63:8 in warnImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:36:4 in console.warn
- node_modules/expo/build/environment/react-native-logs.fx.js:18:4 in warn
- node_modules/react-native/Libraries/ReactNative/AppRegistry.js:200:6 in runApplication
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:416:4 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

Invariant Violation: "outlineWidth" is not a valid style property.
StyleSheet buttonRounded: {
  "alignItems": "center",
  "justifyContent": "center",
  "borderRadius": 999,
  "outlineWidth": 0
}
Valid style props: [
  "alignContent",
  "alignItems",
  etc
  
  This error happens running locally on an Android device with Expo. Please could you fix this? Thank you!

**Comment by taeh98** [comment]
Update: I tried editing Style.js and was able to stop the error. After removing the outlineWidth property from buttonRounded, the same error appears for numberText, which has the same property. After removing it from numberText, there is no longer an error. I'll make a pull request and let you see if it has any other effects I'm unaware of.

**Comment by taeh98** [comment]
Update: I made a pull request with the changes I made that fixed the issue (at least for me) that I described before here: https://github.com/marcocesarato/react-native-input-spinner/pull/31

**Comment by marcocesarato** [comment]
Fixed on v1.4.8. Thanks for report the issue.
