### ISSUE TITLE
Unable to align an input spinner to the vertical centre of the View it is inside of

### ISSUE THREAD

**Issue by taeh98** [marcocesarato/react-native-input-spinner#33]
I am trying to align an input spinner to the vertical centre of a View element which it is inside and am unable to do so. I have been able to align it to the horizontal centre but not the vertical centre. I am trying to do so by using "justifyContent: 'center'" in the style of the View. This worked for buttons in other View elements (each with different background colours, see the image below) but not the input spinner. I set the showBorder attribute of the spinner to true and I think this shows the problem; the spinner element seems to be much larger than the input and buttons themselves (you can see this with the border below the spinner in the image, though the border is faint and thin). It seems this whole area within the border is what is being aligned to the vertical centre rather the inputs themselves. This might be because I am setting the width and height of the spinner manually (width={110} height={36}) but I'm not sure. Please could you help me fix this issue? Perhaps the spinner should not have this excess area below it, or there could be props to choose how to align the spinner within the whole space? Or I could be doing something myself. I'm not totally sure. Thank you!

![image](https://user-images.githubusercontent.com/28008958/107592626-603a4580-6c05-11eb-8e74-2ea0ff1a95a7.png)

**Comment by taeh98** [comment]
This is still an issue for me even after upgrading to version 1.4.9. The picture below shows a view with a red background in which there is a spinner. I have given the spinner backgroundColour: blue in its style prop and background = green as its background prop. Even though the view has "justifyContent: 'center'" in its style prop, the spinner itself still isn't aligned to the vertical centre of the view. This is because of the extra space at the bottom of the spinner element (shown with the blue background of the spinner element but not the actual spinner itself). I also tried using "justifyContent: 'center'" in the style prop for the spinner but this still didn't work.
![image](https://user-images.githubusercontent.com/28008958/107850668-05b70a00-6dfc-11eb-945e-af524a998403.png)

**Comment by marcocesarato** [comment]
I tried using this code:
```
<View style={{flexDirection:"row", height: 500, width: "100%"}}>
						<View style={{flex : 1, backgroundColor:"red", height: 500, justifyContent: 'center', alignItems: 'center'}}>
							<InputSpinner width='auto' height={36}/>
						</View>
						<View style={{flex : 1, backgroundColor:"green", height:500, justifyContent: 'center', alignItems: 'center'}}>
							<Button title="Done"/>
						</View>
						<View style={{flex : 1, backgroundColor:"blue", height:500, justifyContent: 'center', alignItems: 'center'}}>
							<Button title="Back"/>
						</View>
					</View>
```

**Comment by taeh98** [comment]
This is what I get using your code:

![image](https://user-images.githubusercontent.com/28008958/107852437-985da600-6e08-11eb-9180-33168292f335.png)

The spinner is still at the top of its view instead of in the middle (vertically). Do you get the same result? I made sure I'm using version 1.4.9.

This is what I get when I add a yellow background to the style prop of the spinner:

![image](https://user-images.githubusercontent.com/28008958/107852455-aca1a300-6e08-11eb-9e50-2e5512f17e30.png)

It looks like the spinner still has this excess space underneath it. Maybe it's taking up all the room in its parent View element?

**Comment by marcocesarato** [comment]
This is what I see. ![3012.png](https://user-images.githubusercontent.com/36447518/107853337-8a625200-6e15-11eb-97b7-d023d1e614ee.png)

It happen when the spinner have flex: 1 and is not aligned at center. Have you set some styles to the spinner?

**Comment by taeh98** [comment]
I just tried copied and pasting your code directly and it still isn't working for me. I didn't make any changes at all this time and the render() method in my App component is just your code, so there are no parent elements changing styling. I made sure I'm using version 1.4.10.

![image](https://user-images.githubusercontent.com/28008958/107866380-2e74e900-6e68-11eb-918a-c8e250860a38.png)

**Comment by taeh98** [comment]
When trying to debug/understand the problem, I found that if I change the render() method of InputSpinner.js to return just some text and then change it back again (so it's how it was originally), the input spinners are then vertically aligned how I expect, even when I run the app locally (with npm) again. I'm not sure if this might be a clue to fixing the problem.

**Comment by taeh98** [comment]
I just checked again and now when I reclone my repo I'm able to align the spinner elements how I want (even though I tried to do this before and it didn't work then). I'm not sure if it was a weird caching issue of some kind, but thanks for solving this issue anyway!
