### ISSUE TITLE
Going from min to max value when decreasing and vice versa

### ISSUE THREAD

**Issue by EricMclaren** [marcocesarato/react-native-input-spinner#36]
Hi, great work on this component! Is there any way (or any plans) to enable the user to decrease the value from the min and the stepper will go back to the max and vice versa? For example, the min value is 0 and max is 9. When the stepper's value is 0 and the user clicks on the decrease button, it will go to 9. And the same for going up: 9 => 0.

**Comment by marcocesarato** [comment]
Hi,
added this feature on 1.5.0 using prop `continuity`:
Example:
```js
<InputSpinner
	value={this.state.value}
	style={Styles.spinner}
	min={10}
	max={30}
	arrows
	continuity
/>
```

Let me know if any problems occur about this feature.
