### ISSUE TITLE
Warning: Failed prop type: Invalid props.style key `verticalAlign` supplied to `Text`

### ISSUE THREAD

**Issue by ws333** [marcocesarato/react-native-input-spinner#37]
Hi,

after a node_modules delete and rebuild I get this warning when using InputSpinner on Android (not tested on iOS):

```
Warning: Failed prop type: Invalid props.style key `verticalAlign` supplied to `Text`.
Bad object: {
  "color": "#FFFFFF",
  "textAlign": "center",
  "fontSize": 25,
  "fontFamily": null,
  "lineHeight": 37,
  "verticalAlign": "middle"
}
```

Package versions:
```
"react-native": "0.63.4"
"react-native-input-spinner": "^1.4.6"
```

`"verticalAlign": "middle"` was added in this commit:
https://github.com/marcocesarato/react-native-input-spinner/commit/68e0b708d7de4707db17e69971811a00cd33799f

InputSpinner seems to work as before in my case though, but would prefer to get rid of the warning :)

**Comment by marcocesarato** [comment]
Hi, thanks for reporting this issue.
Solved on release v1.5.1.
