### ISSUE TITLE
Hide or Disable one button

### ISSUE THREAD

**Issue by MarkRabey** [marcocesarato/react-native-input-spinner#4]
I have a situation where I'd like to hide or disable one of the buttons. Or possibly overwrite the `onPress` functionality for each button. Is such a thing possible, or planned?

**Comment by marcocesarato** [comment]
> I have a situation where I'd like to hide or disable one of the buttons. Or possibly overwrite the `onPress` functionality for each button. Is such a thing possible, or planned?

At the moment is possible disable only both buttons but you can use `min` and `max` for block one of two (`min` left button `max` right button) or detect if you increased or decreased value and detect which button clicked and when happen you can decide if change or not the value prop.

Anyways I will add in the next release this possibility to disable one of two button 👍

**Comment by marcocesarato** [comment]
Now with version 1.2.7 you can use

| Property                | Description                                                         | Type             | Default          | Note                              |
| ----------------------- | ------------------------------------------------------------------- | ---------------- | ---------------- | --------------------------------- |
| buttonLeftDisabled | Disable left button | Boolean | false |  
| buttonRightDisabled | Disable right button | Boolean | false

**Comment by MarkRabey** [comment]
Perfect! Thanks!

**Comment by morqan** [comment]
hi ,i have litle problem with "buttonLeftDisabled",if it true left button not dissabled,but if "buttonRightDisabled",both button dissabled

**Comment by marcocesarato** [comment]
> hi ,i have litle problem with "buttonLeftDisabled",if it true left button not dissabled,but if "buttonRightDisabled",both button dissabled

I will check the problem. Thank you for your feedback.

**Comment by marcocesarato** [comment]
Fixed on 1.2.8. Let me know its fine @morqan.
