### ISSUE TITLE
Allow a separate step for longPress

### ISSUE THREAD

**Issue by selsamman** [marcocesarato/react-native-input-spinner#40]
I had a need for being able to do slower longPress cycles with larger increments that round the value.  This feels more intuitive and allows larger changes in values more quickly.  It is a common paradigm in the world of appliances.  Omitting longPress leave behavior as is using step value for longPresses.

 Submitted PR #39

**Comment by marcocesarato** [comment]
Hi, thanks for your pull request much appreciated. Merged.
It will probably be available on 1.6.0 soon.
