### ISSUE TITLE
Error loading the "San Francisco" typeface (font) on iOS

### ISSUE THREAD

**Issue by taeh98** [marcocesarato/react-native-input-spinner#45]
When running locally on an iPhone device with Expo, I get the following error:

fontFamily "San Francisco" is not a system font and has not been loaded through Font.loadAsync.
- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
- If this is a custom font, be sure to load it with Font.loadAsync.

I go this error while using version 1.7.2 of this package.

**Comment by marcocesarato** [comment]
Hi,
thanks for reporting this issue.
On iOS "San Francisco" is the default font but in "San Francisco" native reaction it is called "System".
Fixed in the latest version.
