### ISSUE TITLE
input spinner is showing more than max value when value is entered by keypad

### ISSUE THREAD

**Issue by tmtawhid** [marcocesarato/react-native-input-spinner#49]
Here is my input-spinner setting  where max value is 11.  I was able to enter 55 value using Keypad. 

 <View style={{width: 92}}>
            <InputSpinner
              value={count}
              style={GlobalStyle.InputSpinner}
              skin="clean"
              height={35}
              min={0}
              max={11}
              continuity
              maxLength={2}
              editable={true}
              onChange={(num) => {
                setcount(num);
                //alert(num);
              }}              
              fontSize={12}
              buttonFontSize={14}
              colorMax={'#f04048'}
              colorMin={'#42A5F5'}
            />

**Comment by tmtawhid** [comment]
![Screenshot 2021-02-22 074909](https://user-images.githubusercontent.com/15253278/108710760-7b009a00-74e2-11eb-9d6b-dbbfb18c8c77.png)

**Comment by marcocesarato** [comment]
Hi, thanks for reporting this issues.
This issues come probably from release v1.7.0. Now solved on v1.7.6. 
Thanks again for your support.

**Comment by tmtawhid** [comment]
WOW, it is fixed. Thank you so much to  fix this issue.
