### ISSUE TITLE
Issue with decimals

### ISSUE THREAD

**Issue by MarkRabey** [marcocesarato/react-native-input-spinner#5]
I've run into an issue with decimals. When attempting to enter a number manually, for example `1.5`, as soon as the user presses the `.` the value changes to `1.0`. This means I continuously end up entering `1.05` instead. Is there a way around that? A debounce or something maybe on the input?

**Comment by marcocesarato** [comment]
At the moment the only thing that that user can do is use the cursor and set it before the zero and after press 5. If you want solve the problem you can just force the precision as property. If you have another method you can write it and if is a good solution i can implement it a debounce could be good solution and I can try to implement it wait for it.

**Comment by Hirvesh** [comment]
Have the same issue, any solution for this issue?

**Comment by IsmailAlam786** [comment]
i am facing same issue

**Comment by rodrigues-t** [comment]
Have the same issue.

**Comment by sYonashiro** [comment]
I am facing the same issue too

**Comment by ViniciusDalmazzo** [comment]
Have the same issue.

**Comment by mrcehlo** [comment]
I'm facing the same issue! anybody has suggestions on how to overcome this?

**Comment by marcocesarato** [comment]
Now should be solved let me know if all it's ok
