### ISSUE TITLE
Warning: Invalid DOM property `autofocus`. Did you mean `autoFocus`?

### ISSUE THREAD

**Issue by isabellating** [marcocesarato/react-native-input-spinner#54]
Hi, I'm currently getting the above error, but functionality seems to work fine for me. Here's the relevant stack:

Warning: Invalid DOM property `autofocus`. Did you mean `autoFocus`?
    in input (created by TextInput)
    in TextInput (at InputSpinner.js:1314)
    in div (created by View)
    in View (at InputSpinner.js:1309)
    in InputSpinner (at src/index.js:9)

Thank you for this component  by the way, I really like it!

**Comment by marcocesarato** [comment]
Hello,
thanks for reporting this issue, yes it was a mistake, `autofocus` should be `autoFocus`.
Fixed on release "1.7.10"
Thanks again for reporting this issue is appreciated.
