### ISSUE TITLE
Unexpected token (539:10)

### ISSUE THREAD

**Issue by glavermicocca** [marcocesarato/react-native-input-spinner#6]
Goodmorning, intresting prj but i receive this error. How can i solve it? Thanks Giacomo

\node_modules\react-native-input-spinner\index.js: Unexpected token (539:10)

`return <text style={this._getStyleLeftButtonText()}>{text}</text>;`

**Comment by Mauville** [comment]
I got the same error. Upon inspection of the source code, I was trying to run this on "vanilla" react (the non native version).
This has dependencies on the react-native <Text> component.

**Comment by ojinsyo** [comment]
I have the same issues too, how to solve it?
