### ISSUE TITLE
selectTextOnFocus

### ISSUE THREAD

**Issue by sekizlipenguen** [marcocesarato/react-native-input-spinner#9]
<TextInput
                    style={this._getInputTextStyle()}
                    value={this.getValue()}
                    editable={this.isEditable()}
                    keyboardType={this._getKeyboardType()}
                    onChangeText={this.onChange.bind(this)}
                    onSubmitEditing={this.onSubmit.bind(this)}
                    selectTextOnFocus={this.isSelectText()}
                />

    /**
     * Is text input selected
     * @returns {boolean|Boolean}
     */
    isSelectText() {
        return !this.props.selected && this.props.selected;
    }

 selected: PropTypes.bool,

selected: false,

**Comment by marcocesarato** [comment]
On release 1.2.16 is available now the prop `selectTextOnFocus`

**Comment by sekizlipenguen** [comment]
Thanks pro 👍 

returnKeyType? 

 returnKeyType={this._getReturnKeyType()}

    _getReturnKeyType() {
       return this.props.returnKeyType;
     }
InputSpinner.propTypes = {
  returnKeyType:PropTypes.string
}
InputSpinner.defaultProps = {
    returnKeyType: 'done',
}

![Screen Shot 2020-08-06 at 18 47 01](https://user-images.githubusercontent.com/36849861/89552732-3860c400-d815-11ea-9095-0224a9864a91.png)

**Comment by marcocesarato** [comment]
On release 1.2.18 now is available the prop returnKeyType
